export { BooksPage } from './BooksPage/components/BooksPage';
export { GoalsPage } from './GoalsPage/components/GoalsPage';
export { HomePage } from './HomePage/components/HomePage';
export { ProfilePage } from './ProfilePage/components/ProfilePage';
export { ReportsPage } from './ReportsPage/components/ReportsPage';
export { SettingsPage } from './SettingsPage/components/SettingsPage';
export { SignInPage } from './SignInPage/components/SignInPage';
export { SignUpPage } from './SignUpPage/components/SignUpPage';
export { StatisticPage } from './StatisticPage/components/StatisticPage';
