export const routes = {
  bookDetails: () => '/books/$bookId',
  books: () => '/books',
  booksCreate: () => '/books/create',
  booksEdit: () => '/books/edit/$bookId',
  feedback: () => '/feedback',
  goal: () => '/goals/$goalId',
  goals: () => '/goals',
  goalsCreate: () => '/goals/create',
  goalsEdit: () => '/goals/edit/$goalId',
  main: () => '/',
  profile: () => '/profile',
  reports: () => '/reports',
  settings: () => '/settings',
  signIn: () => '/signIn',
  signUp: () => '/signUp',
  statistic: () => '/statistic',
} as const;
