name: CI

on:
  push:
    branches:
      - development
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: http://localhost:3000
    strategy:
      matrix:
        node-version: [20.16.0]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install deps
        run: pnpm i
      - name: linting
        run: pnpm lint
      - name: Tests
        run: pnpm test --verbose
      - name: Build
        run: pnpm build

